local dfp = require 'dfp.api'

go.property("camera_fov", 45)
go.property("camera_near", 0.1)
go.property("camera_far", 1000.0)
go.property("camera_viewport", vmath.vector4(0,0,1,1))
go.property("camera_clear", true)
go.property("camera_clear_color", vmath.vector4())
go.property("camera_clear_depth", 1)
go.property("camera_clear_stencil", 0)

function init(self)
	dfp.__register_camera(go.get_id())
end
